before_install:
  - sudo apt-get update -y
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
  - sudo wget -q https://github.com/ahoy-cli/ahoy/releases/download/2.0.0/ahoy-bin-linux-amd64 -O /usr/local/bin/ahoy && sudo chown $USER /usr/local/bin/ahoy && chmod +x /usr/local/bin/ahoy
  - ahoy up
