version: "3"
services:
  solr:
    build: ./solr
    expose:
      - "8983"
    entrypoint:
      - "docker-entrypoint.sh"
      - "solr-create"
      - "-c"
      - "collection1"
      - "-d"
      - "/config"
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    expose:
      - "3306"
  php:
    build: ./php
    expose:
      - "9000"
    links:
      - db
      - solr
      - memcached
    volumes:
        - "./:/var/www/html"
  nginx:
    build: ./nginx
    ports:
      - "80"
    links:
      - php
    volumes:
        - "./:/var/www/html"
  cli:
    image: kporras07/docker-drupal-cli:v0.10.4
    links:
      - php
      - nginx
      - db
      - solr
      - memcached
      - browser
    volumes:
        - "./:/var/www/html"
        - "~/.ssh:/.ssh"
  memcached:
    image: memcached:1-alpine
    environment:
      # Memcached memory limit in megabytes
      - MEMCACHED_MEMORY_LIMIT=128

  browser:
    image: selenium/standalone-chrome-debug:3.6.0
    # This helps keep selenium-chrome from crashing because it uses shared memory.
    volumes:
      - /dev/shm:/dev/shm
    links:
      - nginx
    ports:
      - "5900"

  share:
    image: fnichol/ngrok
    environment:
      - HTTP_PORT=nginx:80
    links:
      - nginx
    ports:
      - "4040"
  varnish:
    image: thiagofigueiro/varnish-alpine-docker:3.5
    environment:
      - VARNISH_BACKEND_ADDRESS=nginx
      - VARNISH_BACKEND_PORT=80
    links:
      - nginx
    ports:
      - "80"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025"
      - "8025"
