version: "3"
services:
  solr:
    build: ./solr
    expose:
      - "8983"
    entrypoint:
      - "docker-entrypoint.sh"
      - "solr-create"
      - "-c"
      - "collection1"
      - "-d"
      - "/config"
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    expose:
      - "3306"
  php:
    image: kporras07/docker-php:v1.0
    expose:
      - "9000"
    links:
      - db
      - solr
    volumes:
        - "./web:/var/www/html"
  nginx:
    build: ./nginx
    ports:
      - "80"
    links:
      - php
    volumes:
        - "./web:/var/www/html"
  cli:
    image: kporras07/docker-drupal-cli:v0.10.4
    links:
      - php
      - nginx
      - db
      - solr
    volumes:
        - "./web:/var/www/html"
        - "~/.ssh:/.ssh"
