version: "3"
services:
  solr:
    build: ./solr
    expose:
      - "8983"
    entrypoint:
      - "docker-entrypoint.sh"
      - "solr-create"
      - "-c"
      - "collection1"
      - "-d"
      - "/config"
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    expose:
      - "3306"
  php:
    build: ./php
    expose:
      - "9000"
    links:
      - db
      - solr
    volumes:
        - "./docroot:/var/www/html"
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    links:
      - php
    volumes:
        - "./docroot:/var/www/html"
